config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  ActiveAdmin.routes(self)
  root 'feed#fresh'
  get 'profile' => 'users#profile'
  get 'admin/moderate' => 'feed#moderate'
  resources :password_resets, only: [:new, :create, :edit, :update] do
    post :change, on: :collection
  end
  get '/auth/:provider/callback', to: 'sessions#create_external'
  get '/auth/failure', to: 'users#new'

  get 'profile/edit' => 'users#edit_profile'

  get 'photos' => 'feed#photos'
  get 'videos' => 'feed#videos'
  get 'recommend' => 'feed#recommend'
  get 'popular' => 'feed#popular'
  get 'fresh' => 'feed#fresh'
  get 'hits' => 'feed#hits'
  get 'iwant' => 'desires#iwant'

  resources :posts do
    member do
      put :like
      put :basket
      put :change_categories
      put :update_view_counter
    end
    resources :comments
  end
  resources :feedbacks, only: :create
  resources :statistics#, only: :create
  resources :attachments, only: [:create, :destroy] do
    get :clean, on: :collection
  end

  resources :comments
  resources :categories
  resources :tags
  resources :photos
  resources :desires do
    patch :complete, on: :member
    patch :uncomplete, on: :member
    get :offer, on: :member
    resources :offers
  end
  resources :users, except: :edit do
    get :followers, on: :member
    get :analytics, on: :member
    get :following, on: :member
    get :notices, on: :member

    get :basket, on: :member
    get :basket_posts, on: :member
    member do
      get :favourite
      post :follow
      post :follow_several
      post :unfollow
      get :posts
      post 'crop'
      post 'new_ava' => 'users#create_ava'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  namespace :ajax do
    get 'page_description'
    get 'get_cities'
  end

  get 'logout' => 'sessions#destroy'
  get 'trouble' => 'materials#edit'
  get 'feed' => 'feed#show'
  get 'explore' => 'feed#explore'
  get 'signup'  => 'users#new'
  get 'welcome'  => 'sessions#new'
  get 'profile' => 'users#profile'

  get 'main' => 'static_pages#main'
  get 'dev' => 'static_pages#dev'
  get 'terms' => 'static_pages#terms'
  get 'licence' => 'static_pages#licence'
  get 'privacy' => 'static_pages#privacy'
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  skip_before_filter :require_login, except: :show
  before_action :find_city_if_need
  before_action :require_admin, only: :moderate

  def show
  end

  def explore
    if params[:category_name]
      @category = Category.find_by_name(params[:category_name])
      @tag_name = params[:category_name]
      @posts = @category ? Post.category_grid(@category, current_user, @city) : Post.for_user(current_user)
      @posts_path = @category ? category_path(@category) : posts_path
    else
      @tag = Tag.find_by_name(params[:tag_name])
      @tag_name = params[:tag_name] ? ('#' + params[:tag_name]) : 'Популярное'
      @posts_path = @tag ? tag_path(@tag) : posts_path
      @posts = @tag ? Post.tag_grid(@tag, current_user, @city) : Post.for_user(current_user)
    end
    @posts = @posts.standart_limit
  end

  def fresh
    @posts = Post.fresh_grid(current_user, @city)
    respond_to do |f|
      f.json { render json: @posts.limit(params[:count]) }
      f.html { @posts = @posts.standart_limit }
    end
  end

  def moderate
    @posts = Post.moderate_grid
    respond_to do |f|
      f.json { render json: @posts.limit(params[:count]) }
      f.html { @posts = @posts.standart_limit }
    end
  end

  def recommend
    @posts = Post.recommended_grid(current_user, @city)
    respond_to do |f|
      f.json { render json: @posts.limit(params[:count]) }
      f.html { @posts.standart_limit }
    end
  end

  def popular
    @posts = Post.popular_grid(current_user, @city)
    respond_to do |f|
      f.json { render json: @posts.limit(params[:count]) }
      f.html { @posts = @posts.standart_limit }
    end
  end

  def hits
    @posts = Post.hits_grid(current_user, @city)
    respond_to do |f|
      f.json { render json: @posts.limit(params[:count]) }
      f.html { @posts = @posts.standart_limit }
    end
  end
end

app/views/feed/_about_trenly.html.erb
<% if !current_user %>
	<div class = 'join-to-us-under-hat'>
		<div class='contetn-about-trenly'>
			<div class='main-text-profile-link'>
				<div class='main-text'>
					<h2>
						<!--Дизайнеры, художники и мастера ручной работы на нашем сайте смогут вас удивить!-->
						<!--Ищете дизайнерские вещи?</br>Тогда Вы по адресу!-->
						Онлайн-бутики с дизайнерскими товарами и вещами
					</h2>
					<%= link_to "Присоединяйтесь!", new_user_path, class: 'btn btn-primary btn-st'%>
					<div class='we-use-vk-about-trenly'>Мы <a href='https://vk.com/trenly' target='_blank'>Вконтакте</a></div>
				</div>
				<div class='clearboth'>
				</div>
			</div>
		</div>
		<div class='profile-link profile-link1'>
			<a href='http://trenly.ru/users/7'>Страница <b>Awesome Ties</b></a>
		</div>
		<div class='profile-link profile-link2'>
			<a href='http://trenly.ru/users/223'>Мастер <b>Вардуи Погосян</b></a>
		</div>
		<div class='profile-link profile-link3'>
			<a href='http://trenly.ru/users/308'>Мастер <b>Илья Терешин</b></a>
		</div>
		<div class='profile-link profile-link4'>
			<a href='http://trenly.ru/users/126'>Мастер <b>Настя Бугаёва</b></a>
		</div>
		<!--<div class='join-desire'>В разделе <b><%= link_to 'желания', desires_path %></b> напишите 
			то, что Вы хотите найти и купить, а товар найдет Вас сам. Его Вам предложат продавцы.</div>-->
		
	</div>
<% end %>

app/views/feed/_popular_now.html.erb
<div class = 'card-sp'>
  <div class = 'block-title'>
    <a>Актуальное</a>
  </div>
  <div class = 'block-objects tags-feed'>
    <p class="tags-sp">
      <% Tag.where(active: true).each do |t|%>
        <%= link_to "##{t.name}", tag_name_path(t.name) %></br>
      <% end %>
    </p>
  </div>
</div>

app/views/feed/_recommend.html.erb
<div class = 'row' style = 'margin-top: 80px; z-index: 150; display: none;'>
  <div class = 'col-xs-12 wrap-follow-offer'>
    <% if current_user %>
      <div class = 'card-sp follow-offer'>
        <div class = 'title-that-left'>
          Читайте больше людей
        </div>
        <div class = 'list-persons-follow'>
          <% User.recommended_for(current_user).each do |u| %>
          <div class = 'person-follow'>
            <div class = 'person-follow-stat'>
              <%= link_to user_path(u) do %>
                <div class = 'person-follow-photo'
                  style = 'background: url(<%= u.avatar %>)
                    no-repeat; background-size: cover;'>
                </div>
              <% end %>
              <div class = 'person-follow-name'>
                <%= link_to user_path(u) do %>
                <div class="post-autor-name">
                  <span><%= u.name %></span>
                </div>
                <% end %>
                <div class = 'clearboth'>
                </div>
                <div class = 'person-follow-wrap-btn-read'>
                  <%= link_to 'Читать', follow_user_path(u),
                  method: :post,
                  class: 'btn btn-primary btn-st btn-sm',
                  title: 'Хочу получать новости от этого человека',
                  data: { :toggle => 'tooltip', :placement => 'bottom' } %>
                </div>
              </div>
              <div class = 'clearboth'>
              </div>
            </div>
          </div>
          <% end %>

          <div class = 'clearboth'>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/feed/_show_post.html.erb
<div class="modal fade" id = "modal-show-post" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-show-post">
    <div class="modal-content">
      <div class="modal-header">
        <div class='post-autor'>
          <a>
            <div class="usual-avatar" style="background:url(http://studpad.ru/uploads/teacher/avatar/1320/b3d63d8e83.jpg) no-repeat;background-size:cover;">
            </div>
            <div class='post-autor-info'>
              <h4 class="modal-title" id="myModalLabel">Никитин Макс</h4>
              <div>Москва, 1 марта 2016</div>
            </div>
          </a>
        </div>
      </div>
      <div class="modal-body">
        <div class='modal-post-content'>
          <div class='media-content'>
            <img src='https://cs7061.vk.me/c540108/v540108537/18b2b/SqW6tX1Rh18.jpg' />
          </div>
          <div class='media-content'>
            
            <div class="post-type-link extra-background">
              <div class="post-type-link-img">
                <div class="usual-post-photo action-create-element-post">
                  <img src="https://pbs.twimg.com/profile_images/651386816600276993/5E6-28L8_400x400.png">
                </div>
              </div>
              <div class="post-type-link-adress">
                <header class="post-type-link-title">ЮниКредит Банк (@unicreditrussia) | Твиттер</header>
                <div class="post-type-link-description">
                  Последние твиты от ЮниКредит Банк (@unicreditrussia). Официальный Твиттер-канал ЮниКредит Банка. Москва, Россия
                </div>
                <div class="post-type-link-link">
                  <span class="decor-type-link-link" >twitter.com</span>
                </div>
              </div>
            </div>
          </div>
          <div class='text-content'>
            Это развалины древнегреческого города, здесь когда-то в этом старинном амфитеатре собиралась греческая знать. Мы были там во время реставрации, поэтому на фото видны строительные леса)
          </div>
          <div class='comment'>
            <div class='write-comment'>
              <a class="emoji-button" title="&amp;#9786;">☺</a>
              <div class="emoji-wysiwyg-editor" contenteditable="true" placeholder="Введите комментарий и нажмите Enter"></div>
            </div>
            <div class="post-comments">
              <div class="unit-post-comments">
                <div class="preview-object">
                  <div class="preview-object-avatar-comment" style="background:url(https://pp.vk.me/c630725/v630725581/15a68/_K_ZaXrain0.jpg) no-repeat;background-size:cover;"></div>
                  <div class="preview-object-info-mini">
                    <div class="object-text">
                      <div class="object-maintext">
                        <a href="/users/2">YES</a>
                        <span class="post-autor-data">
                          <span> • </span>
                          <span> 1 марта</span>
                        </span>
                        <span>
                          <span class="sign-dots-menu action-angle" data-toggle="dropdown">•••</span>
                          <ul class="dropdown-menu" role="menu">
                            <li>
                              <a>Редактировать</a>
                            </li>
                            <li>
                              <a>Удалить</a>
                            </li>
                          </ul>
                        </span>
                      </div>
                      <div class="text-unit-post-comments emoji-wysiwyg-editor">как Вам такая идея?</div>
                    </div>
                  </div>
                  <div class="clearboth"></div>
                </div>
              </div>

              <div class="unit-post-comments">
                <div class="preview-object">
                  <div class="preview-object-avatar-comment" style="background:url(https://pp.vk.me/c630827/v630827402/19b76/UL_MC3flPVs.jpg) no-repeat;background-size:cover;"></div>
                  <div class="preview-object-info-mini">
                    <div class="object-text">
                      <div class="object-maintext">
                        <a href="/users/2">YES</a>
                        <span class="post-autor-data">
                          <span> • </span>
                          <span> 1 марта</span>
                        </span>
                        <span>
                          <span class="sign-dots-menu action-angle" data-toggle="dropdown">•••</span>
                          <ul class="dropdown-menu" role="menu">
                            <li>
                              <a>Редактировать</a>
                            </li>
                            <li>
                              <a>Удалить</a>
                            </li>
                          </ul>
                        </span>
                      </div>
                      <div class="text-unit-post-comments emoji-wysiwyg-editor">Это самая потрясающая идея</div>
                    </div>
                  </div>
                  <div class="clearboth"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class='modal-atributes'>
          <div class='likes-and-views'>
            <ul>
              <li class='likes'>
                <img src='/images/like_grey.png' /> <span>341</span>
              </li>
              <li class='views'>
                <img src='/images/views.png' /> <span>74563</span>
              </li>
            </ul>
          </div>
          <div class='modal-tags'>
            <h4>Теги</h4>
            <p class="tags-sp">
              <a href="/explore?tag_name=женская мода">#женская мода</a>
              <a href="/explore?tag_name=бенефит косметика">#бенефит косметика</a>
              <a href="/explore?tag_name=urban decay smoky">#urban decay smoky</a>
              <a href="/explore?tag_name=urban decay naked">#urban decay naked</a>
              <a href="/explore?tag_name=urban decay">#urban decay</a>
              <a href="/explore?tag_name=фуллипс">#фуллипс</a>
            </p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/feed/desire.html.erb
<div class='desire-content'>
  <div class='desires-list'>
    <figure>
      <div class="post-autor">
        <a href="#">
          <div class="usual-avatar" style="background:url(https://pp.vk.me/c5382/v5382599/a70/lVMwRxI_h3w.jpg) no-repeat; background-size:cover;"></div>
          <div class="post-autor-info">
            <h4 class="modal-title" id="myModalLabel">Анастасия Носкова</h4>
            <div class='city-time'>
              <span>Уфа</span>
              <span>, </span>
              <span>24 апр.</span>
            </div>
          </div>
        </a>
      </div>
      <div class='post-content-title-text-img'>
        <a href='#'>
          <div class='wrap-title-text'>
            <h3>
              How does your bot say ‘ketchup’?
            </h3>
            <div>
              I didn’t know, so I explored by attempting to make a simple bot to help my family to order in delivery. This proved surprisingly difficult for me. Not because of the technology: as a designer-who-can-code-some, the technical ease of building a bot was exciting. No, the issue I faced wasn’t an argument in code but rather my childhood dinner table: whether to accept ‘catsup’ as a substitute for saying ‘ketchup’.
            </div>
          </div>
          <div class='wrap-img'>
            <img src = 'https://pp.vk.me/c626122/v626122806/22ff/pMDsES72Ydw.jpg' />
          </div>
          <div class='clearboth'>
          </div>
        </a>
      </div>
      <div class='post-footer'>
        <span>16 ответов</span>
      </div>
    </figure>
  </div>
</div>
<div class='feed-content'>
  <div id="grid-gallery" class="grid-gallery">
    <div class='tips-and-comments title-under-hat'>
      <div>Публикации от тех, кого Вы читаете</div>
      <%= link_to fresh_path do%>Посмотреть все свежие публикации<% end %>
    </div>
    <% if current_user.follow_count.zero? %>
      <div class='align-c'>
        <h1>Вы пока еще никого не читаете</h1>
      </div>
    <% else %>
      <%= react_component 'Gallery', posts_url: posts_path(@user) %>
    <% end %>
  </div>
</div>

app/views/feed/explore.slim
= render 'about_trenly'
- if current_user
	.title-explore
	  = @tag_name
- else
	.title-explore.title-explore_lmargin
	  = @tag_name
= render 'partials/city_select'
.grid-gallery
  - unless  !@tag && params[:tag_name]
    = react_component 'ExploreGrid', props: {posts_url: @posts_path + city_params(params[:city_id]), posts_preloaded: scope_serializer(@posts)}, prerender: true
= render "partials/hurry_sing_up"
= render "partials/contacts"

app/views/feed/fresh.slim
= render 'about_trenly'
- if current_user
  .title-explore
    |Новое
- else
  .title-explore.title-explore_lmargin
	|Новое

= render 'partials/city_select'
#grid-gallery.grid-gallery
  #demo
    = react_component 'ExploreGrid',
      props: { posts_preloaded: scope_serializer(@posts),
      posts_url: fresh_path + city_params(params[:city_id])}, prerender: true
= render "partials/hurry_sing_up"
= render "partials/contacts"

app/views/feed/gallery.html.erb
<div class='gallery-items'>
	<!--<div class='wrap-info'>
		<div class='choices'>
	  	<a>
				<div class='choice-no'>
					<img src = '/images/close_gallery.png' />
				</div>
			</a>
			<a>
				<div class='choice-yes'>
					<img src = '/images/like_active.png' />
				</div>
			</a>
		</div>
		<div class='autor-and-attributes'>
			<div class="post-autor">
		    <a href="/users/1">
		      <div class="usual-avatar" style="background: url(/uploads/teacher/avatar/1/thumb_59a4cee392.jpg) no-repeat; background-size: cover; background-color: white;">
		      </div>
		      <div class="post-autor-info">
		        <h4 class="modal-title" id="myModalLabel">Никитин Максим</h4>
		        <div class="city-time">
		          Петровск,  1 мая
		        </div>
		      </div>
		      <div class='clearboth'>
					</div>
				</a>  
		  </div>
		</div>
	</div>
	<div class='wrap-img'>
		<img class='card-butify img-item' src='http://ironlamp.ru/wp-content/uploads/2015/11/o2.jpg' />
	</div> -->
	<%= react_component("ItemsGallery", posts_url: fresh_path) %>
</div>

app/views/feed/hits.slim
= render 'about_trenly'
- if current_user
	.title-explore
	  |Товары дня
- else
	.title-explore_lmargin.title-explore
	  |Товары дня
= render 'partials/city_select'
.tips-and-comments.title-under-title
  |Здесь находятся товары, скидка на которые 10 процентов и более. Успейте купить!
#grid-gallery.grid-gallery
  #demo
    = react_component 'ExploreGrid', prerender: true, props: { posts_url: hits_path + city_params(params[:city_id]), posts_preloaded: scope_serializer(@posts)}

= render "partials/hurry_sing_up"
= render "partials/contacts"

app/views/feed/moderate.slim
= render 'about_trenly'
  .title-explore
    |Модерация
= render 'partials/city_select'
#grid-gallery.grid-gallery
  #demo
    = react_component 'ExploreGrid', props: { posts_url: admin_moderate_path, posts_preloaded: scope_serializer(@posts)}, prerender: true

app/views/feed/photos.html.erb
<%= render 'about_trenly' %>
<% if current_user %>
	<div class='title-explore'>
	  Фотографии
	</div>
<% else %>
	<div class='title-explore title-explore_lmargin'>
	  Фотографии
	</div>
<% end %>
<%= render 'partials/city_select' %>
<div id="grid-gallery" class="grid-gallery">
  <div id='demo'>
    <%= react_component 'Gallery', posts_url: photos_path + city_params(params[:city_id])%>
  </div>
</div>

app/views/feed/popular.slim
= render 'about_trenly'
- if current_user
	.title-explore
	  |Популярное
- else
	.title-explore.title-explore_lmargin
	  |Популярное
= render 'partials/city_select'
#grid-gallery.grid-gallery
  #demo
    = react_component 'ExploreGrid', prerender: true, props: {posts_url: popular_path + city_params(params[:city_id]), posts_preloaded: scope_serializer(@posts)}
= render "partials/contacts"

app/views/feed/recommend.slim
= render 'about_trenly'
- if current_user
	.title-explore
	  |Наш выбор
- else
	.title-explore.title-explore_lmargin
	  |Наш выбор
= render 'partials/city_select'
#grid-gallery.grid-gallery
  #demo
    = react_component 'ExploreGrid', prerender: true, props: {posts_url: recommend_path + city_params(params[:city_id]), posts_preloaded: scope_serializer(@posts) }
= render "partials/hurry_sing_up"
= render "partials/contacts"

app/views/feed/show.html.erb
<div class='feed-content'>
	<div id="grid-gallery" class="grid-gallery">
		<div class='tips-and-comments title-under-hat'>
		  <div>Публикации от тех, кого Вы читаете</div>
		  <%= link_to fresh_path do%>Посмотреть свежие публикации<% end %>
		</div>
    <% if current_user.follow_count.zero? %>
    	<div class='align-c'>
      	<h1 class='impressed-text'>Вы пока еще никого не читаете</h1>
      </div>
    <% else %>
	    <%= react_component 'ExploreGrid', props: { posts_url: posts_path(@user) } %>
    <% end %>
	</div>
	<div class='feed-right-column'>
		<div class='content-feed-right-column'>
			<h4 class='on-grey'>Рекомендуем к просмотру</h4>
			<div class='feed-recomended-list'>
        <% User.recommended.random_order.limit(5).each do |u| %>
  				<div class='person'>
            <%= link_to u do %>
              <div class="usual-avatar"
                style="background: url(<%= u.avatar.thumb %>) no-repeat;
                      background-size: cover";>
              </div>
              <div class='info-person'>
                <h5 class="name-person"><%= u.name %></h5>
                <div class='city-person'><%= u.city_name %></div>
              </div>
              <div class='clearboth'></div>
            <% end %>
          </div>
        <% end %>
			</div>
      <div class='wrap-feed-citizen-list'>
      <% if current_user.city_name %>
  			<h4 class='on-grey'>Бутики и мастера из вашего города</h4>
  			<div class='feed-citizen-list'>
          <% User.having_posts.where.not(id: current_user).where(city: current_user.city).random_order.limit(6).each do |u| %>
    				<div class='person'>
              <%= link_to u do %>
                <div class="usual-avatar"
                  style="background: url(<%= u.avatar.thumb %>) no-repeat;
                        background-size: cover";>
                </div>
                <div class='info-person'>
                  <h5 class="name-person"><%= u.name %></h5>
                  <div class='city-person'><%= u.city_name %></div>
                </div>
                <div class='clearboth'></div>
              <% end %>
            </div>
          <% end %>
  			</div>
      <% end %>
      <%= render "partials/contacts" %>
      </div>
		</div>
	</div>
</div>