config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  ActiveAdmin.routes(self)
  root 'feed#fresh'
  get 'profile' => 'users#profile'
  get 'admin/moderate' => 'feed#moderate'
  resources :password_resets, only: [:new, :create, :edit, :update] do
    post :change, on: :collection
  end
  get '/auth/:provider/callback', to: 'sessions#create_external'
  get '/auth/failure', to: 'users#new'

  get 'profile/edit' => 'users#edit_profile'

  get 'photos' => 'feed#photos'
  get 'videos' => 'feed#videos'
  get 'recommend' => 'feed#recommend'
  get 'popular' => 'feed#popular'
  get 'fresh' => 'feed#fresh'
  get 'hits' => 'feed#hits'
  get 'iwant' => 'desires#iwant'

  resources :posts do
    member do
      put :like
      put :basket
      put :change_categories
      put :update_view_counter
    end
    resources :comments
  end
  resources :feedbacks, only: :create
  resources :statistics#, only: :create
  resources :attachments, only: [:create, :destroy] do
    get :clean, on: :collection
  end

  resources :comments
  resources :categories
  resources :tags
  resources :photos
  resources :desires do
    patch :complete, on: :member
    patch :uncomplete, on: :member
    get :offer, on: :member
    resources :offers
  end
  resources :users, except: :edit do
    get :followers, on: :member
    get :analytics, on: :member
    get :following, on: :member
    get :notices, on: :member

    get :basket, on: :member
    get :basket_posts, on: :member
    member do
      get :favourite
      post :follow
      post :follow_several
      post :unfollow
      get :posts
      post 'crop'
      post 'new_ava' => 'users#create_ava'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  namespace :ajax do
    get 'page_description'
    get 'get_cities'
  end

  get 'logout' => 'sessions#destroy'
  get 'trouble' => 'materials#edit'
  get 'feed' => 'feed#show'
  get 'explore' => 'feed#explore'
  get 'signup'  => 'users#new'
  get 'welcome'  => 'sessions#new'
  get 'profile' => 'users#profile'

  get 'main' => 'static_pages#main'
  get 'dev' => 'static_pages#dev'
  get 'terms' => 'static_pages#terms'
  get 'licence' => 'static_pages#licence'
  get 'privacy' => 'static_pages#privacy'
end

app/views/partials/_administration_data.html.erb
<div class = 'administration-data'>
  © 2015 Studpad </br>
  <a href = '/users/399'>Наш микроблог</a>&nbsp;&nbsp;<a data-toggle="modal" data-target="#modal-send-mail-to-us">Написать письмо</a>
</div>
<%= render '/partials/modal_send_mail_to_us' %>

app/views/partials/_city_select.html.slim
= react_component 'CityFilter', props: { city: @city, current_user: {id: current_user.try(:id), city_id: current_user.try(:city_id) }}

app/views/partials/_class_photos.html.erb
<div id = 'class-photos'>
    <div class = 'row'>
      <div class = 'col-lg-12 col-md-12 col-xs-12'>
        <div class = 'title-background'>
          <div class = 'title-sp' id = 'title-news'>
           Фотографии
          </div>
        </div>
      </div>
    </div>
    <div class = 'row' id = 'each-photos'>
      <div class = 'col-lg-2 col-md-2 col-xs-2' style = 'background: url("https://pp.vk.me/c619119/v619119124/20d41/n51h6svfjtM.jpg"); background-size: cover; height: 120px; cursor: pointer; border: 1px solid white;'>

      </div>
      <div class = 'col-lg-2 col-md-2 col-xs-2' style = 'background: url("https://pp.vk.me/c623926/v623926048/203d3/Fm_NWAvhpss.jpg"); background-size: cover; height: 120px; cursor: pointer; border: 1px solid white;'>

      </div>
      <div class = 'col-lg-2 col-md-2 col-xs-2' style = 'background: url("https://pp.vk.me/c616927/v616927105/1fdfa/_ICExHOk_j8.jpg"); background-size: cover; height: 120px; cursor: pointer; border: 1px solid white;'>

      </div>
      <div class = 'col-lg-2 col-md-2 col-xs-2' style = 'background: url("https://pp.vk.me/c7011/v7011473/255e/6SvvKJTbXb0.jpg"); background-size: cover; height: 120px; cursor: pointer; border: 1px solid white;'>

      </div>
      <div class = 'col-lg-2 col-md-2 col-xs-2' style = 'background: url("https://pp.vk.me/c624121/v624121976/23be6/_QJvC6nWf7E.jpg"); background-size: cover; height: 120px; cursor: pointer; border: 1px solid white;'>

      </div>
      <div class = 'col-lg-2 col-md-2 col-xs-2' style = 'background: url("https://pp.vk.me/c616927/v616927105/1fdfa/_ICExHOk_j8.jpg"); background-size: cover; height: 120px; cursor: pointer; border: 1px solid white;'>
      </div>
    </div>
</div>

app/views/partials/_current_user_info.html.erb
<!-- #Current User Store unsensetive data -->
  <%= javascript_tag do %>
    window.currentUser = {};
    window.currentUser.id = <%= j current_user.id.to_s %>;
    window.currentUser.admin = <%= j current_user.admin?.to_s %>;
    window.currentUser.name = '<%= j current_user.name %>';
    window.currentUser.avatar = '<%= j current_user.avatar.thumb.to_s %>';
    window.currentUser.url = '<%= j user_path(current_user) %>';
    window.currentUser.city_id =  '<%= j current_user.city_id.to_s %>';
    window.currentUser.city_name =  '<%= j current_user.city.try(:name).to_s %>';
    window.categories = [
      <% Category.all.order(name: :asc).each do |c| %>
        { value: <%= c.id %>,
          text: '<%= j c.name %>',
        },
      <% end %>
    ]

    window.cities = [
      <% City.limit(10).each do |c| %>
        { value: <%= c.id %>,
          text: '<%= j c.name %>',
        },
      <% end %>
    ]
  <% end if current_user %>

app/views/partials/_hurry_sing_up.html.erb
<% if !current_user %>
	<div class='road-block-wrapper'>
		<div class='road-block'>
				<h4>Уже спешу!</h4>
				<%= link_to "Зарегистрироваться в Trenly", new_user_path, class: 'btn btn-primary btn-st-contrast'%>
		</div>
	</div>
<% end %>

app/views/partials/_list_subject.html.erb
<%
def classroom_id
    params[:classroom_id] || params[:id]
end
%>
<div class = 'col-lg-2 col-md-2 col-xs-2' id = 'list-subjects'>
  <div id = 'each-subjects'>
    <div class = 'title-sp' id = 'left-main-menu'>
      Меню
    </div>
    <%= link_to classroom_path(classroom_id) do %>
    <div class = 'the-subject'>
      Главная
    </div>
    <% end %>
    <%= link_to classroom_albums_path(classroom_id) do %>
    <div class = 'the-subject'>
      Фотоальбомы
    </div>
    <% end %>
  </div>
  <% if @subjects.present? && current_user %>
    <div id = 'each-subjects'>
      <div class = 'title-sp' id = 'left-main-menu-s'>
        Материалы
      </div>

      <% @subjects.each do |s| %>
        <%= link_to classroom_subject_path(@classroom, s) do %>
        <div class = 'the-subject'>
          <%= s.name %>
        </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/partials/_modal_new_post_link.html.erb
<div class="modal fade" id="modal_new_post_link" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-new-post my-setting-modal-dialog">
      <div class="modal-content modal-content-new-post my-setting-modal-content">
       
          <div class = 'post-autor'> 
            <div class="usual-avatar" style="background: url(
            /uploads/teacher/avatar/1/72b150d9c5.jpg
            ) no-repeat; background-size: cover;">
            </div>
            <div class = 'post-autor-info'>
              <div class = 'post-autor-name'>
                Никитин Макс
              </div>
              <div class = 'post-autor-type'>
                Преподаватель
              </div>
            </div>
          </div>
        
        <div class = "modal-body my-setting-modal-body">
          <div class = 'container-fluid'>
            <div class = 'row'>

              <div class = 'form-new-post'>
                  <div class = 'form-wrap-new-post-type'>
                    <div class = 'extra-background'>
                      <input type = 'text' class = 'input-new-post form-link input-sp form-control' placeholder = 'Введи URL-адрес'/>
                    </div>
                  </div>
                  <div class = 'form-wrap-usual-text'>
                      <textarea class = 'textarea-new-post textarea-sp form-control' placeholder = 'Если хотите, добавьте описание.'></textarea>
                  </div>
              </div>

            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default btn-st-inert" data-dismiss="modal">Закрыть</button>
          <button id = "send-material" type="button" class="btn btn-primary btn-st" data-loading-text = "Подождите..." data-dismiss="modal">Опубликовать</button>
        </div>
      </div>
    </div>
  </div>

app/views/partials/_modal_new_post_material.html.erb
<div class="modal fade" id="modal_new_post_material" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-new-post my-setting-modal-dialog">
      <div class="modal-content modal-content-new-post my-setting-modal-content">
       
          <div class = 'post-autor'> 
            <div class="usual-avatar" style="background: url(
            /uploads/teacher/avatar/1/72b150d9c5.jpg
            ) no-repeat; background-size: cover;">
            </div>
            <div class = 'post-autor-info'>
              <div class = 'post-autor-name'>
                Никитин Макс
              </div>
              <div class = 'post-autor-type'>
                Преподаватель
              </div>
            </div>
          </div>
        
        <div class = "modal-body my-setting-modal-body">
          <div class = 'container-fluid'>
            <div class = 'row'>

              <div class = 'form-new-post'>
                  <div class = 'form-wrap-new-post-type'>
                    <div class = 'drop-zone'>
                      Для загрузки файлов, кликните или перетащите их сюда.
                    </div>
                  </div>
                  <div class = 'form-wrap-usual-text'>
                      <textarea class = 'textarea-new-post textarea-sp form-control' placeholder = 'Если хотите, добавьте описание.'></textarea>
                  </div>
              </div>

            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default btn-st-inert" data-dismiss="modal">Закрыть</button>
          <button id = "send-material" type="button" class="btn btn-primary btn-st" data-loading-text = "Подождите..." data-dismiss="modal">Опубликовать</button>
        </div>
      </div>
    </div>
  </div>

app/views/partials/_modal_send_mail_to_us.html.erb
<div class="modal fade" id="modal-send-mail-to-us" tabindex="-1"
role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <%= form_for(:feedback, url: feedbacks_path) do |f| %>
        <div class="modal-content modal-content-white">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Напишите нам :)</h4>
          </div>
          <div class = "modal-body">
            <div class = 'container-fluid'>
                <div class = 'form-new-post'>
                  <div class = 'form-wrap-usual-text'>
                    <textarea
                      class='textarea-new-post textarea-sp form-control'
                      id = 'feedback_message'
                      name='feedback[message]'
                      placeholder="Введите текст письма"></textarea>
                      <!-- <div placeholder="Введите текст письма" class="text-new-post" contenteditable="true"></div> -->
                  </div>
                </div>
            </div>
          </div>

          <div class="modal-footer">
            <button class="btn btn-default btn-st-inert" data-dismiss="modal">Закрыть</button>
            <%= f.submit 'Отправить', class: "btn btn-primary btn-st"%>
            <!-- <input type="submit" id = "send-material" class="btn btn-primary btn-st" data-loading-text = "Подождите..." data-dismiss="modal"> --><!-- Отправить</input> -->
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/partials/_moderation_rules.html.erb
<div class="modal fade" id = "modal-moderation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-info">
    <div class="modal-content modal-content-info">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2>Модерирование публикаций</h2>
      </div>
      <div class="modal-body">
        <div id='advices' class='advices-of-attract-clients'>
					
					<div class='advices-content'>
						<div class='advices-content-moderation'>
							<p>
								Команда Trenly очень строго модерирует контент, но вы не пугайтесь. Это делается для того, чтобы клиенту было приятно находиться на сайте и любоваться вашими товарами. Общий уровень контента существенно повышает продажи у всех мастеров!
							</p>
							<p>
								Публикации, прошедшие модерацию, помечаются <img src='/images/icon_correct_example.png' width='18' /> в левом нижнем углу на фотографии.
							</p>
							<hr>
							<p>
								<h4 class='moderate-rule'>Что необходимо, чтобы пройти модерацию?</h4>
								<ol>
									<li>
										Товар должен быть хорошего качества;
									</li>
									<li>
										Фотографии должны быть хорошего качества, эстетически приятные, четкие, без ссылок и водяных знаков. Фон, изображенный на фотографии, также важен, как и товар.
									</li>
								</ol>
							</p>
							<hr>
							<p>
								<h4 class='moderate-true'>Публикации, которые <b>прошли</b> модерацию, отображаются в:</h4>
								<ol>
									<li>
										В категориях, которые указал мастер при создании публикации, и в разделе "Новое";
									</li>
									<li>
										На странице мастера;
									</li>
									<li>
										В новостной ленте у тех, кто читает мастера.
									</li>
								</ol>
							</p>
							<hr>
							<p>
								<h4 class='moderate-false'>Публикации, которые <b>не прошли</b> модерацию, отображаются в:</h4>
								<ol>
									<li>
										На странице мастера;
									</li>
									<li>
										В новостной ленте у тех, кто читает мастера.
									</li>
								</ol>
							</p>
						</div>
					</div>
					<!--<h1>Привлеките больше клиентов!</h1>
					<div class='advices-content'>
						<div class='advices-content-introduction'>
							Мы знаем, что этот небольшой текст прочтут не все... Всегда хочется быстрее разместить товар и просто ждать клиентов. Но мы точно уверены в том, что тот, кто потратит 2 минуты на прочтение этих простых советов, сможет привлечь клиентов больше, чем другие!
						</div>
						<h3>Команда Trenly от чистого сердца дает 5 советов:</h3>
						<div class='list-advices'>
							<h4>1. Делать хорошие фотографии</h4>
							<p>
								Единственное, что видит клиент, покупая товар в Интернете, это фотография.
								Успешный мастер заботится не только о качестве своего товара, но и о демонстрации его публике!
								Команда Trenly очень строго модерирует контент! Те публикации, которые прошли модерацию будут опубликованы в категориях, которые указал мастер при 
							</p>
						</div>
					</div> -->
				</div>
      </div>
      <div class="modal-footer">
        <button data-dismiss="modal" aria-hidden="true" class="btn btn-primary btn-st">Хорошо!</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_new_post.html.erb
<div class = 'new-post-buttons card-sp'>
  <div class = 'new-post-wrap'>
    <div class = 'new-post-label' id = 'new-post-label-text'>
      <div class = 'icon-post-text icon-post' data-toggle="modal" data-target="#modal_new_post_text"><img src = '/images/text.png'/></div>
      <span class = 'new-post-label-name'>Текст</span>
    </div>
    <div class = 'new-post-label' id = 'new-post-label-material'>
      <div class = 'icon-post-material icon-post' data-toggle="modal" data-target="#modal_new_post_material"><img src = '/images/attache.png' /></div>
      <span class = 'new-post-label-name'>Файл</span>
    </div>
    <div class = 'new-post-label' id = 'new-post-label-link'>
      <div class = 'icon-post-link icon-post' data-toggle="modal" data-target="#modal_new_post_link"><img src = '/images/link.png' /></div>
      <span class = 'new-post-label-name'>Ссылка</span>
    </div>
    <div class = 'new-post-label' id = 'new-post-label-cite'>
      <div class = 'icon-post-cite icon-post' data-toggle="modal" data-target="#modal_new_post_cite"><img src = '/images/quote.png' /></div>
      <span class = 'new-post-label-name'>Цитата</span>
    </div>
  </div>
  <div class = 'clearboth'>
  </div>
</div>

<%= render "/partials/modal_new_post_text" %>
<%= render "/partials/modal_new_post_material" %>
<%= render "/partials/modal_new_post_link" %>
<%= render "/partials/modal_new_post_cite" %>

app/views/partials/_profile.html.erb
<div class = 'card-sp' id = "profile_user">
  <% if current_user %>

    <div class="block-objects block-user-profile">
      <div class="preview-object">
        <%= link_to user_path(current_user) do %>
        <div class="preview-object-avatar profile-preview-object-avatar" style="background: url(
         <%= current_user.avatar.thumb %>) no-repeat; background-size: cover;">
        </div>
        <div class="preview-object-info profile-preview-object-info">
          <div class="object-name profile-name">Мой микроблог</div>
          <!--<div class="object-text">
            <span class="badge badge-sp each-class">11 А</span> <span class="badge badge-sp each-class">8 В</span> <span class="badge badge-sp each-class">1 класс</span> <span class="badge badge-sp each-class">11 А</span>
          </div>-->
          <% end %>
          <!--<div class = 'switcher'><img class = 'switch' src = '/images/switch9.png' width = '25' height = '25'/></div>-->
          <div class = 'object-text profile-menu'>
            <div>
              <%= link_to 'Настройки', profile_edit_path %>
            </div>
            <div>•
              <%= link_to logout_path, data: { no_turbolink: true } do %>
                Выход
              <% end if current_user %>
            </div>
            <!--<div class = 'btn-group'>
              <span class = 'sign-dots-menu sign-dots-profile-menu' data-toggle="dropdown">•••</span>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to logout_path, data: { no_turbolink: true } do %>
                    Выход
                  <% end if current_user %>
                </li>
              </ul>
            </div>-->
          </div>
        </div>
        <div class = 'clearer'></div>
      </div>
    </div>
  <% else %>
    <div class = "border-t-radius" id = 'feed-card-user'>
      <div class = 'card-sp '>
        <div class = 'feed-profile-background'>
       <div class = "feed-profile-avatar" style="background: url('/empty.png') no-repeat; background-size: cover;">
        </div>
        <div class = "feed-profile-name-email">
          <div class = "feed-profile-name"><%= link_to 'Войти', welcome_path %></div>
          <div class = "feed-profile-email">
            <%= link_to 'Зарегистрироваться', signup_path %>
          </div>
        </div>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_readable_communities.html.erb
<div class = 'card-sp first-left-block'>
  <div class = 'block-title'>
    <%= link_to 'Актуальные сообщества', communities_path %>
    <a></a>
  </div>
  <div class = 'block-objects'>


    <% Community.all.each do |c| %>
    <div class = 'preview-object'>
        <div class = "preview-object-avatar" style="background: url(
        <%= c.avatar %>
        ) no-repeat; background-size: cover;">
        </div>
        <div class="preview-object-info">
          <div class = 'object-name'>
            <%= link_to c.name, community_path(c)%>
          </div>
          <div class = 'object-text'><%= t c.status %></div>
        </div>
    </div>
    <div class = 'clearboth'>
    </div>
    <% end %>

  </div>
</div>

app/views/partials/_view_material.html.erb
<div class="modal fade" id="view_material" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data="create">
  <div class="modal-dialog my-setting-modal-dialog">
    <div class="modal-content my-setting-modal-content">
      <div  class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Просмотр</h4>
      </div>
      <div id='modal-view-the-material'>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>