config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  ActiveAdmin.routes(self)
  root 'feed#fresh'
  get 'profile' => 'users#profile'
  get 'admin/moderate' => 'feed#moderate'
  resources :password_resets, only: [:new, :create, :edit, :update] do
    post :change, on: :collection
  end
  get '/auth/:provider/callback', to: 'sessions#create_external'
  get '/auth/failure', to: 'users#new'

  get 'profile/edit' => 'users#edit_profile'

  get 'photos' => 'feed#photos'
  get 'videos' => 'feed#videos'
  get 'recommend' => 'feed#recommend'
  get 'popular' => 'feed#popular'
  get 'fresh' => 'feed#fresh'
  get 'hits' => 'feed#hits'
  get 'iwant' => 'desires#iwant'

  resources :posts do
    member do
      put :like
      put :basket
      put :change_categories
      put :update_view_counter
    end
    resources :comments
  end
  resources :feedbacks, only: :create
  resources :statistics#, only: :create
  resources :attachments, only: [:create, :destroy] do
    get :clean, on: :collection
  end

  resources :comments
  resources :categories
  resources :tags
  resources :photos
  resources :desires do
    patch :complete, on: :member
    patch :uncomplete, on: :member
    get :offer, on: :member
    resources :offers
  end
  resources :users, except: :edit do
    get :followers, on: :member
    get :analytics, on: :member
    get :following, on: :member
    get :notices, on: :member

    get :basket, on: :member
    get :basket_posts, on: :member
    member do
      get :favourite
      post :follow
      post :follow_several
      post :unfollow
      get :posts
      post 'crop'
      post 'new_ava' => 'users#create_ava'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  namespace :ajax do
    get 'page_description'
    get 'get_cities'
  end

  get 'logout' => 'sessions#destroy'
  get 'trouble' => 'materials#edit'
  get 'feed' => 'feed#show'
  get 'explore' => 'feed#explore'
  get 'signup'  => 'users#new'
  get 'welcome'  => 'sessions#new'
  get 'profile' => 'users#profile'

  get 'main' => 'static_pages#main'
  get 'dev' => 'static_pages#dev'
  get 'terms' => 'static_pages#terms'
  get 'licence' => 'static_pages#licence'
  get 'privacy' => 'static_pages#privacy'
end

app/models/desire.rb
class Desire < ActiveRecord::Base
  belongs_to :user
  has_many :photos, dependent: :destroy, as: :photable
  has_and_belongs_to_many :posts   #генерирует post_ids, posts
end

app/controllers/desires_controller.rb
class DesiresController < ApplicationController
	before_action :find_desire,
    except: [:new, :create, :index, :iwant]
	def new
    @desire = Desire.new
  end

  def create
    @desire = current_user.desires.create desire_params
    render nothing: true
  end

  def index
    @desires = Desire.all.order(created_at: :desc)
  end

  def show
  end

  def offer
  end

  def destroy
    @desire.destroy
    redirect_to desires_path
  end

  def edit
  end

  def iwant
    @desires = current_user.desires.order(created_at: :desc)
  end

  def update
    @desire.update_attributes desire_params
    render nothing: true
  end

  def complete
    @desire.update_attributes(completed: true)
    redirect_to @desire
  end

  def uncomplete
    @desire.update_attributes(completed: false)
    redirect_to @desire
  end

  private
    def desire_params
      params.require(:desire).permit(
        :title, :text, photo_ids: []
      )
    end

    def find_desire
      @desire = Desire.find(params[:id])
    end
end

app/views/desires/edit.slim
= react_component 'StaticDesireForm',
  props: { url: desire_path(@desire),
          desire: {author: {name: @desire.user.name,
                    url: user_path(@desire.user),
                    avatar: @desire.user.avatar.to_s},
          city_id: @desire.user.city_id,
          time: l(@desire.created_at),
          title: @desire.title,
          city_name: @desire.user.city.try(:name),
          text: @desire.text,
          post_type: 'photo',
          photos: @desire.photos.map() do |p| {id: p.id, url: p.url} end,
  }}

app/views/desires/index.html.erb
<div class='iwant-content'>
	<div class='wrap-desires-list'>
		<div class='tips-and-comments title-under-hat'>
		  <div>Читайте желания людей и исполняйте их</div>
      <%= link_to desires_path do %><span class='active'>Все желания</span><% end %> <a>•</a> <%= link_to iwant_path do %><span>Мои желания</span><% end %>
		</div>
    <div class='desires-list'>
      <% @desires.each do |desire| %>
        <figure>
          <div class="post-autor">
            <%= link_to desire.user do %>
              <div class="usual-avatar" style="background:url(<%= desire.user.avatar.thumb %>) no-repeat; background-size:cover;"></div>
            <% end %>
            <div class="post-autor-info">
              <%= link_to desire.user do %>
                <h4 class="modal-title" id="myModalLabel"><%= desire.user.name %></h4>
              <% end %>
              <div class='city-time'>
                <span><%= desire.user.city_name %>, <%= l(desire.created_at) %></span>
              </div>
            </div>
          </div>
          <div class='post-content-title-text-img'>
            <%= link_to desire do %>
              <div class='wrap-title-text'>
                <h3>
                  <%= desire.title %>
                </h3>
                <div>
                  <%= desire.text%>
                </div>
              </div>
              <div class='wrap-img'>
                <% if desire.photos.first %>
                  <img src='<%= desire.photos.first.try :url %>' />
                <% end %>
              </div>
              <div class='clearboth'>
              </div>
            <% end %>
          </div>
          <%= link_to desire do %>
            <div class='post-footer'> 
              <% if current_user != desire.user && !desire.completed %>
                <% if desire.posts.where(user_id: current_user).count < 1 && Post.joins(:desires).where('posts.user_id = (?)', current_user.id).where('desires_posts.created_at > (?)', 1.day.ago).count < 3 %>
                  <%= link_to offer_desire_path(desire) do %>
                    <button type="button" class="btn btn-xs btn-st">
                      Предложить свой товар
                    </button>
                  <% end %>
                <% end %>
              <% end %>
              <span>Ответов: <%= desire.posts.count %></span>
              <% if desire.completed %>
                <h4>Желание исполнено</h4>
              <% end %>
            </div>
          <% end %>
        </figure>
      <% end %>
    </div>
	</div>
	<div class='feed-right-column'>
		<div class='content-feed-right-column'>
      <div>
        <%= link_to new_desire_path do %>
          <button class='btn btn-st'>Написать желание</button>
        <% end %>
        <div class='notification-new-desire'>
          <div class='notification-block'>
            <span>
              Напишите свое желание, а товар найдет Вас сам. Его Вам предложат продавцы.
            </span>
          </div>
        </div>
      </div>
			<h4 class='on-grey'>Рекомендуем к просмотру</h4>
			<div class='feed-recomended-list'>
        <% User.recommended.random_order.limit(5).each do |u| %>
  				<div class='person'>
            <%= link_to u do %>
              <div class="usual-avatar"
                style="background: url(<%= u.avatar.thumb %>) no-repeat;
                      background-size: cover";>
              </div>
              <div class='info-person'>
                <h5 class="name-person"><%= u.name %></h5>
                <div class='city-person'><%= u.city_name %></div>
              </div>
              <div class='clearboth'></div>
            <% end %>
          </div>
        <% end %>
			</div>
      <% if current_user.city_name %>
  			<h4 class='on-grey'>Мастера из вашего города</h4>
  			<div class='feed-citizen-list'>
          <% User.having_posts.where.not(id: current_user).where(city: current_user.city).random_order.limit(5).each do |u| %>
    				<div class='person'>
              <%= link_to u do %>
                <div class="usual-avatar"
                  style="background: url(<%= u.avatar.thumb %>) no-repeat;
                        background-size: cover";>
                </div>
                <div class='info-person'>
                  <h5 class="name-person"><%= u.name %></h5>
                  <div class='city-person'><%= u.city_name %></div>
                </div>
                <div class='clearboth'></div>
              <% end %>
            </div>
          <% end %>
  			</div>
      <% end %>
		</div>
	</div>
</div>
<%= render "partials/contacts" %>

app/views/desires/iwant.html.erb
<div class='iwant-content'>
	<div class='wrap-desires-list'>
		<div class='tips-and-comments title-under-hat'>
		  <div>Здесь находятся Ваши желания</div>
      <%= link_to desires_path do %><span>Все желания</span><% end %> <a>•</a> <%= link_to iwant_path do %><span class='active'>Мои желания</span><% end %>
		</div>
    <div class='desires-list'>
      <% @desires.each do |desire| %>
        <figure>
          <div class="post-autor">
            <%= link_to desire.user do %>
              <div class="usual-avatar" style="background:url(<%= desire.user.avatar.thumb %>) no-repeat; background-size:cover;"></div>
            <% end %>
            <div class="post-autor-info">
              <%= link_to desire.user do %>
                <h4 class="modal-title" id="myModalLabel"><%= desire.user.name %></h4>
              <% end %>
              <div class='city-time'>
                <span><%= desire.user.city_name %>, <%= l(desire.created_at) %></span>
              </div>
            </div>
          </div>
          <div class='post-content-title-text-img'>
            <%= link_to desire do %>
              <div class='wrap-title-text'>
                <h3>
                  <%= desire.title %>
                </h3>
                <div>
                  <%= desire.text%>
                </div>
              </div>
              <div class='wrap-img'>
                <img src='<%= desire.photos.first.try :url %>' />
              </div>
              <div class='clearboth'>
              </div>
            <% end %>
          </div>
          <%= link_to desire do %>
            <div class='post-footer'>
              <span>Ответов: <%= desire.posts.count %></span>
              <% if desire.completed %>
                <h4>Желание исполнено</h4>
              <% end %>
            </div>
          <% end %>
        </figure>
      <% end %>
    </div>
	</div>
	<div class='feed-right-column'>
		<div class='content-feed-right-column'>
      <div>
        <%= link_to new_desire_path do %>
          <button class='btn btn-st'>Написать желание</button>
        <% end %>
        <div class='notification-new-desire'>
          <div class='notification-block'>
            <span>
              Напишите свое желание, а товар найдет Вас сам. Его Вам предложат продавцы.
            </span>
          </div>
        </div>
      </div>
			<h4 class='on-grey'>Рекомендуем к просмотру</h4>
			<div class='feed-recomended-list'>
        <% User.recommended.random_order.limit(5).each do |u| %>
  				<div class='person'>
            <%= link_to u do %>
              <div class="usual-avatar"
                style="background: url(<%= u.avatar.thumb %>) no-repeat;
                      background-size: cover";>
              </div>
              <div class='info-person'>
                <h5 class="name-person"><%= u.name %></h5>
                <div class='city-person'><%= u.city_name %></div>
              </div>
              <div class='clearboth'></div>
            <% end %>
          </div>
        <% end %>
			</div>
      <% if current_user.city_name %>
  			<h4 class='on-grey'>Мастера из вашего города</h4>
  			<div class='feed-citizen-list'>
          <% User.having_posts.where.not(id: current_user).where(city: current_user.city).random_order.limit(5).each do |u| %>
    				<div class='person'>
              <%= link_to u do %>
                <div class="usual-avatar"
                  style="background: url(<%= u.avatar.thumb %>) no-repeat;
                        background-size: cover";>
                </div>
                <div class='info-person'>
                  <h5 class="name-person"><%= u.name %></h5>
                  <div class='city-person'><%= u.city_name %></div>
                </div>
                <div class='clearboth'></div>
              <% end %>
            </div>
          <% end %>
  			</div>
      <% end %>
		</div>
	</div>
</div>
<%= render "partials/contacts" %>

app/views/desires/new.slim
= react_component 'StaticDesireForm', props: {time_now: l(Time.now)}
= render "partials/contacts"

app/views/desires/offer.html.erb
<div class='desire-content'>
  <div class="post-autor">
    <%= link_to @desire.user do %>
      <div class="usual-avatar" style = 'background: url(<%= @desire.user.avatar.thumb %>) no-repeat; background-size: cover; background-color: white;'>
      </div>
      <div class="post-autor-info">
        <h4 class="modal-title" id="myModalLabel"><%= @desire.user.name %></h4>
        <div class='city-time'>
          <%= @desire.user.city_name %>, <%= l(Time.now) %>
        </div>
      </div>
    <% end %>
    <% if current_user == @desire.user %>
      <button class='btn-neutral btn btn-st'>
        Удалить
      </button>
    <% end %>
  </div>

  <div class='post-title desire-title'>
    <h1><%= @desire.title %></h1>
  </div>

  <div class='post-description desire-description'>
    <div class="usual-desire-text-create action-create-element-desire">
      <%= @desire.text %>
    </div>
  </div>

  <div class='post-img desire-img'>
    <img src = '<%= @desire.photos.first.try :url %>' />
  </div>

  <div class="post-footer desire-footer">
    <% if current_user == @desire.user %>
      <button type="button" class="btn btn-primary btn-st">
        Спасибо, желание исполнено!
      </button>
    <% else %>
      <%= link_to @desire do %>
          Посмотреть все предложенные товары
      <% end %>
    <% end %>
  </div>

  <div class="desire-variants">
    <% if !@desire.completed %>
      <% if @desire.posts.where(user_id: current_user).count > 0 %>
        <div class='tips-and-comments'>Вы уже предложили свой товар. Человек получил об этом уведомление.</div>
      <% else %>
        <% if Post.joins(:desires).where('posts.user_id = (?)', current_user.id).where('desires_posts.created_at > (?)', 1.day.ago).count > 2 %>
          <div class='tips-and-comments'>Вы можете предлагать только свой товар только 3 людям в сутки, поэтому предлагайте не всем подряд, а только тем, кому Вы действительно можете помочь.</div>
        <% else %>
          <div class='tips-and-comments'>
            Предложите человеку свой товар, если он соответствует его желанию! Вы можете предложить ему только один товар.
          </div>
          <div id="grid-gallery" class="grid-gallery">
            <% if current_user.posts.count.zero? %>
              <div class='align-c'>
                <h1 class='impressed-text'>Вы ничего не можете предложить, у Вас нет публикаций</h1>
              </div>
            <% else %>
              <%= react_component 'ExploreGrid', props: {posts_url: posts_user_path(current_user), desire_id: @desire.id, desire_count: @desire.posts.where(user_id: current_user).count, person_count: Post.joins(:desires).where('posts.user_id = (?)', current_user.id).where('desires_posts.created_at > (?)', 1.day.ago).count }%>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/desires/show.html.erb
<div class='desire-content'>
  <div class="post-autor">
    <%= link_to @desire.user do %>
      <div class="usual-avatar" style = 'background: url(<%= @desire.user.avatar.thumb %>) no-repeat; background-size: cover; background-color: white;'>
      </div>
      <div class="post-autor-info">
        <h4 class="modal-title" id="myModalLabel"><%= @desire.user.name %></h4>
        <div class='city-time'>
          <%= @desire.user.city_name %>, <%= l(Time.now) %>
        </div>
      </div>
    <% end %>

    <div class="action-angle post-action">
      <div class="btn-group">
        <span class="sign-dots-menu-big" data-toggle="dropdown">•••</span>
        <ul class="dropdown-menu blue-background-dropdown-menu" role="menu">
          <% if current_user == @desire.user && !@desire.completed %>
            <li>
              <%= link_to edit_desire_path do %>Редактировать<% end %>
            </li>
            <li>
              <%= link_to 'Удалить', desire_path(@desire),
              method: :delete,
              data: { confirm: 'Вы уверены?' } %>
            </li>
          <% end %>
          <li>
            <a>Пожаловаться</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class='post-title desire-title'>
    <h1><%= @desire.title %></h1>
  </div>

  <div class='post-description desire-description'>
    <div class="usual-desire-text-create action-create-element-desire">
      <%= @desire.text %>
    </div>
  </div>

  <div class='post-img desire-img'>
    <img src = '<%= @desire.photos.first.try :url %>' />
  </div>

  <div class="post-footer desire-footer">
    <% if @desire.completed %>
        <h4 class='complete-desire'>Желание исполнено</h4>
        <% if current_user == @desire.user %>
          <div>Вы уже, наверное, выбрали товар, который Вам по душе)) Теперь осталось связаться с его продавцом</div></br></br>
          <%= simple_form_for(@desire, url: uncomplete_desire_path) do |f| %>
            <%= f.button :submit, "Продолжить исполнение желания", class: 'btn btn-st btn-neutral' %>
          <% end %>
        <% end %>
    <% else %>
      <% if current_user == @desire.user %>
        <%= simple_form_for(@desire, url: complete_desire_path) do |f| %>
          <%= f.button :submit, "Спасибо, желание исполнено!", class: 'btn btn-primary btn-st' %>
        <% end %>
      <% else %>
        <% if @desire.posts.where(user_id: current_user).count > 0 %>
          <span class='short-essay-on-gray'>Вы уже предложили свой товар. Человек получил уведомление о Вашем предложении.</span>
        <% else %>
          <% if Post.joins(:desires).where('posts.user_id = (?)', current_user.id).where('desires_posts.created_at > (?)', 1.day.ago).count > 2 %>
            <span class='short-essay-on-gray'>Вы можете предлагать только свой товар только 3 людям в сутки, поэтому предлагайте не всем подряд, а только тем, кому Вы действительно можете помочь.</span>
          <% else %>
            <%= link_to offer_desire_path do %>
              <button type="button" class="btn btn-primary btn-st">
                Предложить свой товар
              </button>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="desire-variants">
    <div class='tips-and-comments'>Ответов (<%= @desire.posts.count %>)</div>
    <div id="grid-gallery" class="grid-gallery">
      <%= react_component 'ExploreGrid', props: {posts_url: desire_offers_path(@desire)} %>
    </div>
  </div>

</div>
<%= render "partials/contacts" %>