config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  ActiveAdmin.routes(self)
  root 'feed#fresh'
  get 'profile' => 'users#profile'
  get 'admin/moderate' => 'feed#moderate'
  resources :password_resets, only: [:new, :create, :edit, :update] do
    post :change, on: :collection
  end
  get '/auth/:provider/callback', to: 'sessions#create_external'
  get '/auth/failure', to: 'users#new'

  get 'profile/edit' => 'users#edit_profile'

  get 'photos' => 'feed#photos'
  get 'videos' => 'feed#videos'
  get 'recommend' => 'feed#recommend'
  get 'popular' => 'feed#popular'
  get 'fresh' => 'feed#fresh'
  get 'hits' => 'feed#hits'
  get 'iwant' => 'desires#iwant'

  resources :posts do
    member do
      put :like
      put :basket
      put :change_categories
      put :update_view_counter
    end
    resources :comments
  end
  resources :feedbacks, only: :create
  resources :statistics#, only: :create
  resources :attachments, only: [:create, :destroy] do
    get :clean, on: :collection
  end

  resources :comments
  resources :categories
  resources :tags
  resources :photos
  resources :desires do
    patch :complete, on: :member
    patch :uncomplete, on: :member
    get :offer, on: :member
    resources :offers
  end
  resources :users, except: :edit do
    get :followers, on: :member
    get :analytics, on: :member
    get :following, on: :member
    get :notices, on: :member

    get :basket, on: :member
    get :basket_posts, on: :member
    member do
      get :favourite
      post :follow
      post :follow_several
      post :unfollow
      get :posts
      post 'crop'
      post 'new_ava' => 'users#create_ava'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  namespace :ajax do
    get 'page_description'
    get 'get_cities'
  end

  get 'logout' => 'sessions#destroy'
  get 'trouble' => 'materials#edit'
  get 'feed' => 'feed#show'
  get 'explore' => 'feed#explore'
  get 'signup'  => 'users#new'
  get 'welcome'  => 'sessions#new'
  get 'profile' => 'users#profile'

  get 'main' => 'static_pages#main'
  get 'dev' => 'static_pages#dev'
  get 'terms' => 'static_pages#terms'
  get 'licence' => 'static_pages#licence'
  get 'privacy' => 'static_pages#privacy'
end

app/models/user.rb
class User < ActiveRecord::Base
  self.inheritance_column = false

  include DestroyedAt
  authenticates_with_sorcery!
  acts_as_voter
  acts_as_followable
  acts_as_follower

  before_validation :remove_whitespaces
  before_validation :parse_social

  has_many :notifications
  has_many :posts
  has_many :comments
  has_many :feedbacks
  has_many :desires, dependent: :destroy
  has_one  :basket
  has_many :statistics, dependent: :destroy
  belongs_to :city

  scope :recommended, -> { where(recommended: true) }
  scope :random_order, -> { order('RANDOM()') }
  scope :having_posts, -> {
    where('users.id IN (SELECT DISTINCT posts.user_id FROM posts)')
  }

  delegate :name, to: :city, allow_nil: true, prefix: true

  validates :password,
    length:       {message: 'Не менее 5 символов', minimum: 5},
    presence:     {message: 'Не может быть пустым'},
    confirmation: {message: 'Пароли не совпадают'},
    on:           :create
  validates :email, uniqueness: {message: 'Такой email уже занят'}, presence: true
  validates :name, presence: true
  validates :terms_of_service, acceptance: true, on: :create

  mount_uploader :avatar, AvatarUploader

  def get_basket
    if basket
      basket
    else
      create_basket!
    end
  end

  after_update :recommended_notification

  def recommended_notification
    notifications.recommendation.create if self.recommended_changed? && self.recommended
  end

  def recommended_users
    User.none
  end

  def self.recommended_for(user)
    if user
      where.not(id: [user.id] + user.all_follows.map(&:followable_id))
        .recommended.random_order.limit(3)
    else
      recommended.limit(3)
    end
  end

  def site_url
    if self.school.to_s.starts_with? 'http'
      self.school
    else
      "//" + self.school.to_s
    end
  end

  def city_id= (id)
    self[:city_id] = id.present? ? City.load_external_data(id).id : nil
  end

  private
    def parse_social
      if vk_id
        vk_id.gsub!('https://www.vk.com/', '')
        vk_id.gsub!('http://www.vk.com/', '')
        vk_id.gsub!('www.vk.com/', '')
        vk_id.gsub!('https://vk.com/', '')
        vk_id.gsub!('http://vk.com/', '')
        vk_id.gsub!('vk.com/', '')
        vk_id.gsub!('@', '')
      end
      if facebook_id
        facebook_id.gsub!('https://www.facebook.com/', '')
        facebook_id.gsub!('www.facebook.com/', '')
        facebook_id.gsub!('https://facebook.com/', '')
        facebook_id.gsub!('facebook.com/', '')
        facebook_id.gsub!('@', '')
      end
      if instagram_id
        instagram_id.gsub!('https://www.instagram.com/', '')
        instagram_id.gsub!('www.instagram.com/', '')
        instagram_id.gsub!('https://instagram.com/', '')
        instagram_id.gsub!('instagram.com/', '')
        instagram_id.gsub!('@', '')
      end
    end

    def remove_whitespaces
      self.email = email.to_s.downcase.squish
      self.type = 'teacher'
    end

end

app/models/user/sign_in.rb
class User::SignIn < ActiveType::Object
  attribute :email, :string
  attribute :password, :string

  validates :email, presence: true
  validates :password, presence: true

  def set_error
    errors.add(:email, 'Неверные данные')
    errors.add(:password, ' ')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login,
    only: [:new, :create, :show, :basket_posts, :posts]

  before_action :find_user,
    except: [:new, :create, :profile, :edit_profile]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      auto_login @user
      # @user.recommended_users.each do |u|
      #   @user.follow(u)
      #   u.follow(@user)
      # end
      flash[:success] = 'Успешная регистрация'
      #UserMailer.welcome(@user).deliver_later

      redirect_to @user
    else
      @button_name = 'Создать'
      render 'new'
    end
  end

  def edit
  end

  def edit_profile
    @user = current_user
    render 'edit'
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = 'Данные успешно изменены'
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def posts
    render json: Post.profile_grid(@user).limit(params[:count])
  end

  def show
    if !current_user || current_user != @user && !current_user.admin?
      @user.statistics.profile_show.create
    end
  end

  def basket_posts
    @posts = @user.get_basket.posts.order(created_at: :desc).limit(params[:count])
    render 'posts/index', formats: :json
  end

  def follow
    current_user.follow(@user)
    Notification.follow.find_or_create_by!(user: @user, who: current_user)
    redirect_to :back
  end

  def unfollow
    current_user.stop_following(@user)
    Notification.follow.where(
      user: @user,
      who: current_user).destroy_all
    redirect_to :back
  end

  def follow_several
    #byebug
    User.where(id: params[:user_ids]).limit(5).each do |u|
      @user.follow(u)
    end
    render nothing: true
  end

  def create_ava
    a = Attachment.create(file: params[:avatar])
    render json: { url: a.file.url, attachment_id: a.id  }
  end

  def crop
    a = Attachment.find(params[:attachment_id])
    @user.update_attribute :avatar, a.file.file
    a.destroy
    @user.avatar.crop(params[:crop_x], params[:crop_y], params[:crop_w],
     params[:crop_h], params[:height], params[:width])
    @user.save! #нахождение этой строчки именно здесь важно
    @user.avatar.recreate_versions!

    redirect_to user_path
  end

  def profile
    @user = current_user
    render 'show'
  end

  def destroy
    #@user.remove_avatar!
    @user.destroy
    redirect_to root_path
  end

  def favourite
    respond_to do |f|
      f.json do
        @posts = @user.get_voted(Post).order(created_at: :desc).limit(params[:count])
        render json: @posts
      end
      f.html {}
    end
  end

  def analytics
  end


  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :phone,
        :instagram_id, :vk_id, :description, :city_id, :facebook_id,
        :school, :password, :password_confirmation, :terms_of_service)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	
	def halffull_contacts?(user)
		phone_contact = 0
		vk_contact = 0
		facebook_contact = 0
		insta_contact = 0

		phone_contact = 1 if user.phone.present?
		vk_contact = 1 if user.vk_id.present?
		facebook_contact = 1 if user.facebook_id.present?
		insta_contact = 1 if user.instagram_id.present?

		number_of_contact = phone_contact + vk_contact + facebook_contact + insta_contact
		number_of_contact > 1
	end

end

app/views/users/_followers_block.html.erb
<div class = 'profile-followers'>
  <div class = 'wrap-element-profile-followers'>
    <% if @user.posts.count != 0 %>
      <%= link_to user_path(@user) do %>
        <div class = 'element-profile-followers'>
            <p>Публикации</p>
            <%= @user.posts.count %>
        </div>
      <% end %>
    <% end %>
    <% if @user.get_voted(Post).count != 0 %>
      <%= link_to favourite_user_path(@user) do %>
        <div class = 'element-profile-followers'>
            <p>Нравится</p>
            <%= @user.get_voted(Post).count %>
        </div>
      <% end %>
    <% end %>
    <% if @user.followers_count != 0 %>
      <%= link_to followers_user_path(@user) do %>
        <div class = 'element-profile-followers'>
          <% if @user != current_user %>
            <p>Читатели</p>
          <% else %>
            <p>Меня читают</p>
          <% end %>
          <%= @user.followers_count %>
        </div>
      <% end %>
    <% end %>
    <% if @user.follow_count != 0 %>
      <%= link_to following_user_path(@user) do %>
        <div class = 'element-profile-followers'>
          <% if @user != current_user %>
            <p>Читает</p>
          <% else %>
            <p>Я читаю</p>
          <% end %>
          <%= @user.follow_count %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_instruction.html.erb
<% if current_user && current_user == @user && Time.now - current_user.created_at < 1.day%>

	<div class='instruction-for-user'>
		<div class='about-instruction'>Эти подсказки пропадут спустя сутки после регистрации</div>
		<div class='instruction-block'>
			<div class='notification-block'>
				<div class='text'>
	     	 Если Вы что-то творите и созидаете, то <b><%= link_to 'опубликуйте', new_post_path %></b> свой товар, чтобы он появился на сайте и Вас заметили клиенты.
	    	</div>
	    	<div class='img'>
	    		<img src='/images/coins.png' />
	    	</div>
	    </div>
	    <div class='notification-block'>
	    	<div class='text'>
	      	Посмотрете самые интересные товары мастеров. Для этого сверху выберите <b>категорию</b> и перейдите в интересующий Вас раздел.
	      </div>
	      <div class='img'>
	    		<img src='/images/coffee.png' />
	    	</div>
	    </div>
	    <div class='notification-block'>
	    	<div class='text'>
	      	Осуществляйте <b><%= link_to 'желания', desires_path %></b> других людей! Предложите им свой товар.</br>
	      	Или же <b><%= link_to 'напишите свое желание', new_desire_path %></b>, а товар найдет Вас сам.
	      </div>
	      <div class='img'>
	    		<img src='/images/rocket.png' />
	    	</div>
	    </div>
	  </div>
	</div>
	<div class='clearboth'>
   </div>
<% end %>

app/views/users/_left_branch_profile.html.erb
<div class='card-sp'>
  <div class = 'profile-avatar_img border-t-radius' style = 'background: url(<%= @user.avatar %>) no-repeat; background-size: cover; background-color: white;'>
  </div>
  <div class = 'action-angle'>
    <% if @user == current_user %>
    <div class = 'btn-group'>
      <span class = 'sign-dots-menu profile-setting' data-toggle="dropdown">•••</span>
      <ul class="dropdown-menu blue-background-dropdown-menu" role="menu">
        <li>
          <%= link_to 'Мои настройки', profile_edit_path %>
          <%= link_to 'Выход', logout_path, data: { no_turbolink: true } %>
        </li>
      </ul>
    </div>
    <% end %>
  </div>
  <div class = 'profile-info'>
    <div class = 'profile-info_name'><%= @user.name %></div>
    <div class = 'profile-info_city'><%= @user.city.try(:name) %></div>
    <% if @user.description.present? %>
      <div class = 'profile-info_description'>
        <%= @user.description %>
      </div>
    <% end %>
    <% if @user.school.present? %>
      <%= link_to @user.site_url, target: :blank do %>
        <div class = 'profile-info_school'>
          <%= @user.school %>
        </div>
      <% end %>
    <% end %>
    <% if @user.vk_id.present? %>
      <div class = 'profile-info_vk'>
        <%= link_to "https://vk.com/#{@user.vk_id}", target: :blank do %>
          <img src= '/images/vk.png' /> <%= @user.vk_id %>
        <% end %>
      </div>
    <% end %>
    <% if @user.instagram_id.present? %>
      <div class = 'profile-info_insta'>
        <%= link_to "https://www.instagram.com/#{@user.instagram_id}", target: :blank do %>
          <img src= '/images/insta.png' /> <%= @user.instagram_id %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<!--<div class = 'bar-profile card-sp'>
  <%#= link_to user_path(@user) do %>
    <div>
        <span class="badge pull-right"><%#= @user.posts.count %></span>
        <img src='/images/publication.png' /> Публикации
    </div>
  <%# end %>
  <%#= link_to basket_user_path(@user) do %>
    <div>
        <span class="badge pull-right"><%#= @user.get_basket.posts.count %></span>
        <img src='/images/delicious_active.png' /> Самое вкусное
    </div>
  <%# end %>
</div>-->

app/views/users/_profile_user.html.erb
<span class='social-networks'>
    <% if current_user && @user != current_user %>
      <% if current_user.following?(@user) %>
        <%= link_to 'Читаю', unfollow_user_path(@user),
        method: :post,
        class: 'btn btn-primary btn-st btn-follow btn-follow-on',
        data: { toggle: 'tooltip', placement: 'bottom' } %>
      <% else %>
        <%= link_to 'Читать', follow_user_path(@user),
        method: :post,
        class: 'btn btn-primary btn-st',
        data: { toggle: 'tooltip', placement: 'bottom' } %>
      <% end %>
    <!-- <button class = 'btn btn-primary btn-st'>Читать</button> -->
    <% end %>
    <% if current_user && @user == current_user || current_user && current_user.admin? %>
      <%= link_to analytics_user_path(@user), class: 'link-stats' do %>
        Статистика
      <% end %>
      &nbsp;•&nbsp;
      <%= link_to profile_edit_path do %>
        Настройки профиля
      <% end %>
    <% end %>
    <% if current_user %>
      <h5><%= @user.phone %></h5>
      <p>
        <%= react_component 'SocialInfo', props:{ user: {id: @user.id, vk_id: @user.vk_id, facebook_id: @user.facebook_id, instagram_id: @user.instagram_id}}%>
      </p>
    <% else %>
      <div class='notification-block notification-more-contact'>
        <%= link_to 'Войдите', welcome_path %> на Trenly, чтобы связаться с продавцом
      </div>
    <% end %>
    <% if current_user == @user && !halffull_contacts?(current_user)%>
      <div class='notification-block notification-more-contact'>
        <%= link_to profile_edit_path do %>Укажите<% end %> больше контактов, чтобы с Вами было легче связаться!
      </div>
    <% end %>
</span>
<div class='avatar'>
  <div class='img-avatar' style = 'background: url(<%= @user.avatar %>) no-repeat; background-size: cover; background-color: white;'></div>
</div>
<div class='name'>
  <%= @user.name %>
</div>
<% if @user.description.present? %>
  <div class='aboutme'>
    <%= @user.description %>
  </div>
<% else %>
  <% if @user == current_user %>
    <div class='aboutme'>
      <%= link_to profile_edit_path do %>
        Добавить контакты и информацию о себе
      <% end %>
    </div>
  <% end %>
<% end %>
<% if @user.city.present? %>
  <div class='city'>
    <%= @user.city.try(:name) %>
  </div>
<% else %>
  <% if @user == current_user %>
    <div class='city'>
      <%= link_to profile_edit_path do %>
        Укажите город
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/favourite.html.erb
<div class='wrap-profile'>
  <%= render "profile_user" %>
  <div class='menu'>
	  <ul>
	    <li>
	      <span><%= @user.posts.count %></span>
	      <%= link_to user_path(@user) do %>
	        Публикации
	      <% end %>
	    </li>
	    <li class='active'>
	      <span><%= @user.get_voted(Post).count %></span>
	      <%= link_to favourite_user_path(@user) do %>
	        Нравится
	      <% end %>
	    </li>
	    <li>
	      <span><%= @user.follow_count %></span>
	      <%= link_to following_user_path(@user) do %>
	        <% if @user != current_user %>
	          Читает
	        <% else %>
	          Я читаю
	        <% end %>
	      <% end %>
	    </li>
	    <li>
	      <span><%= @user.followers_count %></span>
	      <%= link_to followers_user_path(@user) do %>
	        <% if @user != current_user %>
	          Читатели
	        <% else %>
	          Меня читают
	        <% end %>
	      <% end %>
	    </li>
	  </ul>
	</div>
</div>
<div id="grid-gallery" class="grid-gallery">
  <%= react_component 'ExploreGrid', props: {posts_url: favourite_user_path(@user)} %>
</div>
<%= render "partials/contacts" %>

app/views/users/followers.html.erb
<div class='wrap-profile'>
  <%= render "profile_user" %>
  <div class='menu'>
    <ul>
      <li>
        <span><%= @user.posts.count %></span>
        <%= link_to user_path(@user) do %>
          Публикации
        <% end %>
      </li>
      <li>
        <span><%= @user.get_voted(Post).count %></span>
        <%= link_to favourite_user_path(@user) do %>
          Нравится
        <% end %>
      </li>
      <li>
        <span><%= @user.follow_count %></span>
        <%= link_to following_user_path(@user) do %>
          <% if @user != current_user %>
            Читает
          <% else %>
            Я читаю
          <% end %>
        <% end %>
      </li>
      <li class='active'>
        <span><%= @user.followers_count %></span>
        <%= link_to followers_user_path(@user) do %>
          <% if @user != current_user %>
            Читатели
          <% else %>
            Меня читают
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<div class='card-butify center-block602'>
  <div class="card-title">
    <% if @user != current_user %>
      <p>Читают</p>
    <% else %>
      <p>Меня читают</p>
    <% end %>
  </div>
  <div class="usual-list border-b-radius">
    <div class = 'followers'>
      <% @user.followers.each do |u|%>
      <div class = 'follower'>
        <div class="follower-user-button">
          <div class='follower-user'>
            <div class="preview-object">
                <div class="preview-object-avatar" style="background: url(
                <%= u.avatar.thumb %>
                ) no-repeat; background-size: cover;">
                </div>
                <div class="preview-object-info">
                  <div class="object-text">
                    <div class="object-maintext">
                      <%= link_to u.name, user_path(u)%>
                    </div>
                  </div>
                </div>
            </div>
            <div class="clearboth">
            </div>
          </div>
          <div class = 'follower-button'>
          </div>
        </div>
        <div class="clearboth">
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>
<%= render "partials/contacts" %>

app/views/users/following.html.erb
<div class='wrap-profile'>
  <%= render "profile_user" %>
  <div class='menu'>
    <ul>
      <li>
        <span><%= @user.posts.count %></span>
        <%= link_to user_path(@user) do %>
          Публикации
        <% end %>
      </li>
      <li>
        <span><%= @user.get_voted(Post).count %></span>
        <%= link_to favourite_user_path(@user) do %>
          Нравится
        <% end %>
      </li>
      <li class='active'>
        <span><%= @user.follow_count %></span>
        <%= link_to following_user_path(@user) do %>
          <% if @user != current_user %>
            Читает
          <% else %>
            Я читаю
          <% end %>
        <% end %>
      </li>
      <li>
        <span><%= @user.followers_count %></span>
        <%= link_to followers_user_path(@user) do %>
          <% if @user != current_user %>
            Читатели
          <% else %>
            Меня читают
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<div class='card-butify center-block602'>
  <div class="card-title">
    <% if @user != current_user %>
      <p>Читает</p>
    <% else %>
      <p>Я читаю</p>
    <% end %>
  </div>
  <div class="usual-list border-b-radius">
    <div class = 'followers'>
      <% @user.all_following.each do |u|%>
      <div class = 'follower'>
        <div class="follower-user-button">
          <div class='follower-user'>
            <div class="preview-object">
                <div class="preview-object-avatar" style="background: url(
                <%= u.avatar.thumb %>
                ) no-repeat; background-size: cover;">
                </div>
                <div class="preview-object-info">
                  <div class="object-text">
                    <div class="object-maintext">
                      <%= link_to u.name, user_path(u)%>
                    </div>
                  </div>
                </div>
            </div>
            <div class="clearboth">
            </div>
          </div>
          <div class = 'follower-button'>
            <%= link_to 'Не читать', unfollow_user_path(u),
                method: :post,
                class: 'btn btn-primary btn-st btn-reject-follow',
                data: { toggle: 'tooltip', placement: 'bottom' } if current_user == @user %>
          </div>
        </div>
        <div class="clearboth">
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "partials/contacts" %>

app/views/users/new.html.erb
<div class = 'form-create-new-object animated zoomIn'>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
    <h1>Регистрация</h1>
    <p>У Вас уже есть профиль на Trenly?
      <%= link_to "Войдите!", welcome_path %>
    </p>

    <%= simple_form_for(@user, url: users_path, html: { class: 'form-vertical' }) do |f| %>
      <%= f.input :name, label: false, input_html: { class: 'input-sp', placeholder: 'Название Вашего бутика или магазина' } %>
      <%= f.input :email, label: false, input_html: { class: 'input-sp',  placeholder: 'Электронный адрес' } %>
      <%= f.select :city_id, [], { include_blank: true }, {id: 'user_city_id'} %>
      <%= f.input :password, label: false, input_html: { class: 'input-sp',  placeholder: 'Придумайте пароль' } %>
      <%= f.input :password_confirmation, label: false,  input_html: { class: 'input-sp',  placeholder: 'Повторите пароль' } %>
      <div class = 'reg-licence'>
        <%= f.input :terms_of_service, as: :boolean,
          label: "Я принимаю #{link_to 'правила сайта', terms_path}  и #{link_to 'лицензионное соглашение', licence_path}.".html_safe %>
      </div>
      <%= f.button :submit, button_name(@user), class: 'btn-st btn-primary' %>
      <%= link_to '/auth/vkontakte', class: 'link-to-reg-vk btn btn-st vk-link-page-new-session-and-reg' do%>
        <img src='/images/vk_link_reg1.png'/> Войти через ВК
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<%= render "partials/contacts" %>

app/views/users/notices.html.erb
<div class ='container' id = 'main-container'>
  <div class='card-butify center-block602'>
    <div class="card-title">
      Уведомления
    </div>
    <div class="usual-list border-b-radius">
      <div class = 'followers'>
        <% @user.notifications.order(created_at: :desc).limit(30).each do |n| %>
          <div class = 'follower'>
            <div class='follower-user-button'>
              <div class='follower-user'>
                <div class="preview-object">
                    <% if n.who %>
                      <div class="preview-object-avatar" style="background: url(
                      <%= n.who.avatar.thumb %>
                      ) no-repeat; background-size: cover;">
                      </div>
                    <% end %>
                    <div class="preview-object-info">
                      <div class="object-text">
                        <div class="object-maintext">
                          <% if n.recommendation? %>
                            <span>Поздравляем! Команда Trenly добавила Вас в список пользователей, рекомендованных к просмотру</span>
                          <% elsif n.offer? %>
                            <%= link_to n.who.name, user_path(n.who), class: 'thin-text300' %>
                            <span>предложил(а) Вам свой товар</span>
                          <% elsif n.post_recommendation? %>
                            <span>Команде Trenly понравилась Ваша <b><%= link_to 'публикация', post_path(n.post_id) %></b>, она добавлена в категорию <b><%= link_to 'Наш выбор', recommend_path %></b>
                            </span>
                          <% elsif n.who %>
                            <%= link_to n.who.name, user_path(n.who), class: 'thin-text300' %>
                            <% if n.comment? %>
                            <span>прокоментировал(а)</span>
                            <%= link_to 'эту', post_path(n.post_id) %>
                            <span>публикацию</span>
                            <% elsif n.like? %>
                            <span>понравилась</span>
                            <%= link_to 'эта', post_path(n.post_id) %>
                             <span>публикация</span>
                            <% else %>
                            <span>начал(а) читать Вас</span>
                            <% end %>
                          <% end %>
                        </div>
                        <div class="object-subtext-data">
                          <%= l n.created_at %>
                        </div>
                      </div>
                    </div>
                </div>
                <div class="clearboth">
                </div>
              </div>
              <div class = 'follower-button'>
                <img src = '<%= n.image_path %>' />
              </div>
            </div>
            <div class="clearboth">
            </div>
          </div>
        <% end %>
        <% @user.notifications.where(viewed: false).update_all(viewed: true) %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='wrap-profile'>
  <%= render "profile_user" %>
  <div class='menu'>
	  <ul>
	    <li class='active'>
	      <span><%= @user.posts.count %></span>
	      <%= link_to user_path(@user) do %>
	        Публикации
	      <% end %>
	    </li>
	    <li>
	      <span><%= @user.get_voted(Post).count %></span>
	      <%= link_to favourite_user_path(@user) do %>
	        Нравится
	      <% end %>
	    </li>
	    <li>
	      <span><%= @user.follow_count %></span>
	      <%= link_to following_user_path(@user) do %>
	        <% if @user != current_user %>
	          Читает
	        <% else %>
	          Я читаю
	        <% end %>
	      <% end %>
	    </li>
	    <li>
	      <span><%= @user.followers_count %></span>
	      <%= link_to followers_user_path(@user) do %>
	        <% if @user != current_user %>
	          Читатели
	        <% else %>
	          Меня читают
	        <% end %>
	      <% end %>
	    </li>
	  </ul>
	</div>
</div>
<%= render "instruction" %>
<div id="grid-gallery" class="grid-gallery">
  <%= react_component 'ExploreGrid', props: {
  	posts_preloaded: scope_serializer(Post.profile_grid(@user).standart_limit),
  	posts_url: posts_user_path(@user)
  	}, prerender: true %>
</div>
<%= render "partials/contacts" %>